FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./apps/http-server ./apps/http-server 
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun  install 
RUN bun run db:gen

EXPOSE 8081

CMD ["bun" , "run" , "index.ts"]