FROM bun/oven:1

WORKDIR /usr/src/app

COPY ./apps/websocket ./apps/websocket
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

RUN bun i 
RUN bun run db:gen

EXPOSE 8082

CMD ["bun" , "run" , "index.ts"]